corrected conflict between Graph Name and Release Name
gchq/Kai pull request #41
Opened 2020-07-09 09:19 UTC by p3430233

2020-07-09 09:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gchq/Kai?pullRequest=41) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gchq/Kai?pullRequest=41) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gchq/Kai?pullRequest=41) it.</sub>

2020-07-09 10:00 UTC, d47853 requested changes
Thanks @p3430233. 

Rather than converting the graphId / graph name to a release name and using that for everything, it would be better to use both in the deployment. So use the release_name as the Helm release name (when you call `helm_client.install_chart(release_Name, values=values_file`) and the graph_name as the graphId (when you construct the values file for example).

Apart from that, I'm pretty happy with it. Though you'll need to update the graph-database-test.ts file as you've changed the primary key.

2020-07-09 10:00 UTC, d47853 commented on lib/rest-api/lambdas/add_graph_request.py
> +                "releaseName": release_Name,
Might be worth adding the graph name to this object too.

2020-07-09 10:00 UTC, d47853 commented on lib/rest-api/lambdas/add_graph_request.py
> +        "releaseName": release_Name,
You'll need to add the graph Id to this too as the GraphId will be used by the worker.

2020-07-09 10:00 UTC, d47853 commented on lib/workers/lambdas/add_graph.py
> +                "releaseName": release_Name
The graphId / graph_name should be used here

2020-07-09 10:00 UTC, d47853 commented on lib/workers/lambdas/add_graph.py
> +def create_values(release_Name, schema, security_groups):
This should be renamed to graph_name to avoid confusion

2020-07-09 10:00 UTC, d47853 commented on lib/workers/lambdas/add_graph.py
> +    values = create_values(release_Name, schema, security_groups)
You want to pass the graph_name here

2020-07-13 14:01 UTC, t11947 commented on lib/rest-api/lambdas/add_graph_request.py
> +def lowercase_graph_name(graph_Name):
Consider removing or renaming method as this specific of an abstraction seems a little unnecessary. Perhaps consider calling function format_graph_name or similar, in case the method of formatting the graph name changes in future.

2020-07-13 14:01 UTC, t11947 commented on lib/rest-api/lambdas/add_graph_request.py
> +def is_graph_name_valid(graph_Name):
Typically the snake case convention is all lower case.

2020-07-16 09:13 UTC, d47853 requested changes
The other lambdas (For Delete and Get) will need to be updated also - at the moment they reference the old graphId field. You need to update the tests as well to make the CI pass

2020-07-16 09:13 UTC, d47853 commented on lib/workers/lambdas/add_graph.py
> +                "graphName": graph_name
```suggestion
                "graphId": graph_name
```

2020-08-12 10:10 UTC, d47853 approved these changes

2020-08-13 10:23 UTC, d47853 requested changes

2020-08-13 10:23 UTC, d47853 commented on bin/kai.ts
> +new AppStack(app, "KaiStackp", {
```suggestion
new AppStack(app, "KaiStack", {
```

2020-08-13 10:23 UTC, d47853 commented on bin/kai.ts
> +    stackName: "KaiStackp"
```suggestion
    stackName: "KaiStack"
```

2020-08-13 10:23 UTC, d47853 commented on lib/rest-api/lambdas/graph/__init__.py
> +
```suggestion
```

2020-08-13 10:23 UTC, d47853 commented on lib/rest-api/lambdas/delete_graph_request.py
> +def format_graph_name(graph_name):
Just a suggestion and not necessarily a deal breaker but to reduce duplication, perhaps we could move this to a python util file and reference it from both the add_graph_request and delete_graph_request lamdas?

2020-08-13 10:23 UTC, d47853 commented on lib/workers/lambdas/graph/__init__.py
> +        print(response)
We try and use loggers but again not a deal breaker.

2020-08-18 09:46 UTC, d47853 approved these changes

2020-08-18 09:46 UTC, merged